*Pandas Concepts *

*What is Pandas*
Pandas is a fast, powerful, flexible and easy to use open source data analysis and manipulation tool, built on top of the Python programming language.

# **Pandas Series**
A Pandas Series is like a column in a table. It is a 1-D array holding data of any type.

In [ ]:
import pandas as pd
import numpy as np

Series from lists

In [ ]:
# string
country = ['India','Pakistan','USA','Nepal','Srilanka']

pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [ ]:
# integers
runs = [13,24,56,78,100]

runs_ser = pd.Series(runs)

[link text](https://)

In [ ]:
# custom index
marks = [67,57,89,100]
subjects = ['maths','english','science','hindi']

pd.Series(marks,index=subjects)

maths       67
english     57
science     89
hindi      100
dtype: int64

In [ ]:
# setting a name
marks = pd.Series(marks,index=subjects,name='Nitish ke marks')
marks

maths       67
english     57
science     89
hindi      100
Name: Nitish ke marks, dtype: int64


# Series From the Dictionaries

In [ ]:
marks = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks,name='nitish ke marks')
marks_series

maths       67
english     57
science     89
hindi      100
Name: nitish ke marks, dtype: int64

### Series Attributes

In [ ]:
# size
marks_series.size

4

In [ ]:
# dtype
marks_series.dtype

dtype('int64')

In [ ]:
# name
marks_series.name

'nitish ke marks'

In [ ]:
# is_unique
marks_series.is_unique

pd.Series([1,1,2,3,4,5]).is_unique

False

In [ ]:
# index
marks_series.index

Index(['maths', 'english', 'science', 'hindi'], dtype='object')

In [ ]:
runs_ser.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
# values
marks_series.values

array([ 67,  57,  89, 100])

In [ ]:
# with one col
subs = pd.read_csv('/content/subs.csv',squeeze=True)
subs

In [ ]:
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no',squeeze=True)
vk

In [ ]:
# head and tail
subs.head()

In [ ]:
vk.head(3)

In [ ]:
vk.tail(10)

In [ ]:
# sample
movies.sample(5)

In [ ]:
# value_counts -> movies
movies.value_counts()

In [ ]:
# sort_values -> inplace
vk.sort_values(ascending=False).head(1).values[0]

In [ ]:
vk.sort_values(ascending=False)

In [ ]:
# sort_index -> inplace -> movies
movies.sort_index(ascending=False,inplace=True)

In [ ]:
vk.sort_values(inplace=True)

# Series Maths Methods

In [ ]:
 # count
vk.count()

In [ ]:
# sum -> product
subs.sum()

In [ ]:
# mean -> median -> mode -> std -> var
subs.mean()
print(vk.median())
print(movies.mode())
print(subs.std())
print(vk.var())

In [ ]:
# min/max
subs.max()

In [ ]:
# describe
subs.describe()

# Series Indexing

In [ ]:
# integer indexing
x = pd.Series([12,13,14,35,46,57,58,79,9])
x

In [ ]:
# negative indexing
x[-1]

In [ ]:
movies

In [ ]:
vk[-1]

In [ ]:
marks_series[-1]

In [ ]:
# slicing
vk[5:16]

In [ ]:
# negative slicing
vk[-5:]

In [ ]:
movies[::2]

In [ ]:
# fancy indexing
vk[[1,3,4,5]]

In [ ]:
# indexing with labels -> fancy indexing
movies['2 States (2014 film)']

In [ ]:
# using indexing
marks_series[1] = 100
marks_series

In [ ]:
 #what if an index does not exist
marks_series['evs'] = 100

In [ ]:
marks_seriesd

In [ ]:
# slicing
runs_ser[2:4] = [100,100]
runs_ser

In [ ]:
# fancy indexing
runs_ser[[0,3,4]] = [0,0,0]
runs_ser

In [ ]:
# using index label
movies['2 States (2014 film)'] = 'Alia Bhatt'
movies

# Copy and Views

# Series with Python Functionalities

In [ ]:
# len/type/dir/sorted/max/min
print(len(subs))
print(type(subs))
print(dir(subs))
print(sorted(subs))
print(min(subs))
print(max(subs))

In [ ]:
# type conversion
list(marks_series)

In [ ]:
dict(marks_series)

In [ ]:
# membership operator

'2 States (2014 film)' in movies

In [ ]:
'Alia Bhatt' in movies.values

In [ ]:
# looping
for i in movies.index:
  print(i)

In [ ]:
# Arithmetic Operators(Broadcasting)
100 + marks_series

In [ ]:
# Relational Operators

vk >= 50

Boolean Indexing on Series

In [ ]:
# Find no of 50's and 100's scored by kohli
vk[vk >= 50].size

In [ ]:
# find number of ducks
vk[vk == 0].size

In [ ]:
# Count number of day when I had more than 200 subs a day
subs[subs > 200].size

In [ ]:
# find actors who have done more than 20 movies
num_movies = movies.value_counts()
num_movies[num_movies > 20]

# Plotting Graphs on Series

In [ ]:
subs.plot()

In [ ]:
movies.value_counts().head(20).plot(kind='pie')

# Some Important Series Methods

In [ ]:
# astype
# between
# clip
# drop_duplicates
# isnull
# dropna
# fillna
# isin
# apply
# copyd

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
subs = pd.read_csv('/content/subs.csv',squeeze=True)
subs

In [ ]:
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no',squeeze=True)
vk

In [ ]:
vk = pd.read_csv('/content/kohli_ipl.csv',index_col='match_no',squeeze=True)
vk

In [ ]:
# astype
import sys
sys.getsizeof(vk)

In [ ]:
sys.getsizeof(vk.astype('int16'))

In [ ]:
# between
vk[vk.between(51,99)].size

In [ ]:
# clip
subsd

In [ ]:
subs.clip(100,200)

In [ ]:
# drop_duplicates
temp = pd.Series([1,1,2,2,3,3,4,4])
temp

In [ ]:
temp.drop_duplicates(keep='last')

In [ ]:
temp.duplicated().sum()

In [ ]:
vk.duplicated().sum()

In [ ]:
movies.drop_duplicates()

In [ ]:
temp = pd.Series([1,2,3,np.nan,5,6,np.nan,8,np.nan,10])
temp

In [ ]:
temp.size

In [ ]:
temp.count()

In [ ]:
# isnull
temp.isnull().sum()

In [ ]:
# dropna
temp.dropna()

In [ ]:
# fillna
temp.fillna(temp.mean())

In [ ]:
# isin
vk[(vk == 49) | (vk == 99)]

In [ ]:
vk[vk.isin([49,99])]

In [ ]:
# apply
movies

In [ ]:
movies.apply(lambda x:x.split()[0].upper())

In [ ]:
subs

In [ ]:
subs.mean()

In [ ]:
# copy